#ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: brainbox-redis-configmap
  namespace: brainbox
data:
  REDIS_HOST: "brainbox-redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainbox-redis-deployment
  namespace: brainbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brainbox-redis
  template:
    metadata:
      labels:
        app: brainbox-redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        envFrom:
        - configMapRef:
            name: brainbox-redis-configmap
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"

---
#Service
apiVersion: v1
kind: Service
metadata:
  name: brainbox-redis-service
  namespace: brainbox
spec:
  type: NodePort
  selector:
    app: brainbox-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30006