apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: brainbox-promtail-role
  namespace: brainbox
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]