apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: brainbox-promtail-rolebinding
  namespace: brainbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: brainbox-promtail-role
subjects:
- kind: ServiceAccount
  name: brainbox-promtail-serviceaccount
  namespace: brainbox