apiVersion: v1
kind: Secret
metadata:
  name: brainbox-postgresql-secret
  namespace: brainbox
type: Opaque
stringData:
  postgres-password: postgres
  brainboxusersadmin-password: brainboxusersadmin
  brainboxchatsadmin-password: brainboxchatsadmin