apiVersion: v1
kind: Service
metadata:
  name: brainbox-postgresql-service
  namespace: brainbox
spec:
  type: NodePort
  selector:
    app: brainbox-postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30002