apiVersion: v1
kind: Service
metadata:
  name: brainbox-client-service
  namespace: brainbox
spec:
  type: NodePort
  selector:
    app: brainbox-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000