"""Initial tables creation

Revision ID: 0d578fbd9aa4
Revises: 
Create Date: 2025-05-28 11:10:29.028635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d578fbd9aa4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_chat')
    op.drop_table('audio_chat')
    op.drop_table('image_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_chat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_from_user', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_uid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text)"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('image_chat_pkey'))
    )
    op.create_table('audio_chat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_from_user', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('audio_uid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text)"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audio_chat_pkey'))
    )
    op.create_table('text_chat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_from_user', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text)"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('text_chat_pkey'))
    )
    # ### end Alembic commands ###
