apiVersion: v1
kind: Secret
metadata:
  name: brainbox-neural-secret
  namespace: brainbox
type: Opaque
stringData:
  MINIO_SECRET_KEY: "minioadmin"
  POSTGRES_URL: "postgresql+asyncpg://brainboxchatsadmin:brainboxchatsadmin@brainbox-postgresql-service.brainbox.svc.cluster.local:5432/brainboxchats"
  RABBITMQ_URL: "amqp://brainboxrabbitmq:brainboxrabbitmq@brainbox-rabbitmq-service.brainbox.svc.cluster.local:5672/"
  FOLDER_ID: "folder-id"
  OAUTH_TOKEN: "your-token"