apiVersion: v1
kind: Service
metadata:
  name: brainbox-neural-service
  namespace: brainbox
spec:
  type: ClusterIP
  selector:
    app: brainbox-neural
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002