"""Initial migration

Revision ID: d3f2d6b6bb96
Revises: 
Create Date: 2025-04-06 16:00:10.051828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3f2d6b6bb96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='ID пользователя',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Уникальная почта пользователя',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=20),
               comment='Уникальное имя пользователя',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Хэш пароля пользователя (bcrypt)',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата и время создания записи (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text)"))
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата и время последнего входа в запись (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text)"))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата и время последнего входа в запись (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text)"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата и время создания записи (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text)"))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Хэш пароля пользователя (bcrypt)',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Уникальное имя пользователя',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Уникальная почта пользователя',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID пользователя',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
