#Secret
apiVersion: v1
kind: Secret
metadata:
  name: brainbox-rabbitmq-secret
  namespace: brainbox
type: Opaque
stringData:
  username: guest
  password: guest

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainbox-rabbitmq-deployment
  namespace: brainbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brainbox-rabbitmq
  template:
    metadata:
      labels:
        app: brainbox-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: brainbox-rabbitmq-secret
              key: username
        - name: RABBITMQ_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: brainbox-rabbitmq-secret
              key: password
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"

---
#Service
apiVersion: v1
kind: Service
metadata:
  name: brainbox-rabbitmq-service
  namespace: brainbox
spec:
  type: NodePort
  selector:
    app: brainbox-rabbitmq
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
    nodePort: 30004
  - name: management
    protocol: TCP
    port: 15672
    targetPort: 15672
    nodePort: 30005