apiVersion: v1
kind: Service
metadata:
  name: brainbox-grafana-service
  namespace: brainbox
spec:
  type: NodePort
  selector:
    app: brainbox-grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31001