apiVersion: v1
kind: Service
metadata:
  name: brainbox-minio-service
  namespace: brainbox
spec:
  type: ClusterIP
  selector:
    app: brainbox-minio
  ports:
  - name: api
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: console
    protocol: TCP
    port: 9001
    targetPort: 9001