apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: brainbox-minio-statefulset
  namespace: brainbox
spec:
  serviceName: brainbox-minio-service
  replicas: 1
  selector:
    matchLabels:
      app: brainbox-minio
  template:
    metadata:
      labels:
        app: brainbox-minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        args: ["server", "/data", "--console-address", ":9001"]
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: minio-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: minio-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi