apiVersion: v1
kind: Secret
metadata:
  name: brainbox-gateway-secret
  namespace: brainbox
type: Opaque
stringData:
  RABBITMQ_URL: "amqp://brainboxrabbitmq:brainboxrabbitmq@brainbox-rabbitmq-service.brainbox.svc.cluster.local:5672/"