apiVersion: v1
kind: Service
metadata:
  name: brainbox-gateway-service
  namespace: brainbox
spec:
  type: NodePort
  selector:
    app: brainbox-gateway
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30001