apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brainbox-redis-persistentvolumeclaim
  namespace: brainbox
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi