apiVersion: v1
kind: Service
metadata:
  name: brainbox-redis-service
  namespace: brainbox
spec:
  type: ClusterIP
  selector:
    app: brainbox-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379