apiVersion: v1
kind: Service
metadata:
  name: brainbox-authentication-service
  namespace: brainbox
spec:
  type: ClusterIP
  selector:
    app: brainbox-authentication
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001