apiVersion: v1
kind: Service
metadata:
  name: brainbox-prometheus-service
  namespace: brainbox
spec:
  type: ClusterIP
  selector:
    app: brainbox-prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090